trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

jobs:
- job: TheiaBinary
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.13'
      # windows:
      #   imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
    displayName: Install - Python 2.7
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: Install - Node.js 10.x
  - script: yarn
    displayName: Install - Theia Dependencies
    env:
      GITHUB_TOKEN: $(Personal.GitHub.Token)
  - script: yarn build
    displayName: Build - Theia Application
  - script: yarn package
    displayName: Package - Theia Binary
  - bash: cd ./dist/ && mkdir ./bin/ && zip -r -9 ./bin/theia-$(Agent.OS)-bin.zip ./node_modules/ ./theia
    displayName: 'Archive - Theia Application'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: ./dist/bin/
      artifactName: 'Theia Binary'
    displayName: 'Publish - Theia Binary'
